// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // shadowDatabaseUrl is optional; use DIRECT_URL if provided in env
    shadowDatabaseUrl: process.env["DIRECT_URL"] || undefined,
  },
});